default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  username: root
  password: <%= ENV.fetch('SECRET_RAILS_DB_PASSWORD') %>
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: theultimatesciencefictionawardwinningbooksinternetdatabase_development

test:
  <<: *default
  database: theultimatesciencefictionawardwinningbooksinternetdatabase_test

production:
  <<: *default
  host: db
  database: theultimatesciencefictionawardwinningbooksinternetdatabase
  password: root
